config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: "businesses#index"
  
  resources :businesses do
    resources :orders, only: [:index, :create]
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: :create
      collection do
        get 'search'
      end
  end
  resources :users, only: [:show]
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_show, only: [:edit, :update]

  def index
    @businesses = Business.order('created_at DESC')
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    if @business.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @business.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    if @business.user_id == current_user.id
    else
      redirect_to root_path
    end
  end

  def update
    if @business.update(business_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    if @business.user_id == current_user.id
      @business.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def search
    if params[:q]&.dig(:name)
      squished_keywords = params[:q][:name].squish
      params[:q][:name_cont_any] = squished_keywords.split(" ")
    end
    @q = Business.ransack(params[:q])
    @business = @q.result
  end

  private

  def set_business
    @business = Business.find(params[:id])
  end


  def business_params
    params.require(:business).permit(:name, :text, :category_id, :prefecture_id, :price,:company, images: []).merge(user_id: current_user.id)
  end

  def redirect_to_show
    return redirect_to root_path if current_user.id != @business.user.id
  end

end

app/views/businesses/edit.html.erb
<div class="businesses-new-contents">
  <header class="businesses-new-header">
  <%= link_to image_tag("logo.png", class: :logo, size: '160x60'), "/" %>
  </header>

  <div class="businesses-new-main">
    <h2 class="businesses-new-title">情報を入力してね！</h2>
    <%# 仕事体験紹介画像%>
    <%= render partial: 'shared/form' %>
    <%# /仕事体験紹介画像%>
    <%= form_with model: @business, id: 'new_business', local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%end%>
  </div>
  <footer class="business-new-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('logo.png' , size: '185x50'), "/" %>
  </footer>

</div>

app/views/businesses/index.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# 画面上部写真部分%>
  <div class='title-contents'>
  <%= video_tag("/videos/production ID_4957770.mp4", autoplay: :true, loop: :true, muted: :true, class: 'video-content') %>
  </div>
    <div class="wrap">
    <div class="wrap slide-paused" ontouchstart="">
      <ul class="slideshow">
        <li class="content content-hover"><%= link_to image_tag("621763_s.jpg", size: "300x200"), "/" %><br>sample</li>
        <li class="content content-hover"><%= link_to image_tag("3665067_s.jpg", size: "300x200"), "/" %><br>sample</li>
        <li class="content content-hover"><%= link_to image_tag("1341441_s.jpg", size: "300x200"), "/" %><br>sample</li>
        <li class="content content-hover"><%= link_to image_tag("22882887_s.jpg", size: "300x200"), "/" %><br>sample</li>
      </ul>
      <ul class="slideshow">
        <li class="content content-hover"><%= link_to image_tag("621763_s.jpg", size: "300x200"), "/" %><br>sample</li>
        <li class="content content-hover"><%= link_to image_tag("1341441_s.jpg", size: "300x200"), "/" %><br>sample</li>
        <li class="content content-hover"><%= link_to image_tag("3665067_s.jpg", size: "300x200"), "/" %><br>sample</li>
        <li class="content content-hover"><%= link_to image_tag("22882887_s.jpg", size: "300x200"), "/" %><br>sample</li>
      </ul>
      <ul class="slideshow">
        <li class="content content-hover"><%= link_to image_tag("621763_s.jpg", size: "300x200"), "/" %><br>sample</li>
        <li class="content content-hover"><%= link_to image_tag("1341441_s.jpg", size: "300x200"), "/" %><br>sample</li>
        <li class="content content-hover"><%= link_to image_tag("3665067_s.jpg", size: "300x200"), "/" %><br>sample</li>
        <li class="content content-hover"><%= link_to image_tag("22882887_s.jpg", size: "300x200"), "/" %><br>sample</li>
      </ul>
    </div>
  </div>
  <%# /画面上部写真部分%>

  <%# 体験一覧%>
  <div class='experience-contents'>
    <h2 class='title'>体験一覧</h2>
    <ul class='experience-lists'>
      <% @businesses.each do |business|%>
      <li class='list'>
        <%= link_to business_path(business.id) do %>
          <div class='business-img-content'>
            <%= image_tag business.images[0], class: "business-img" %>

          </div>
          <% end %>
          <div class='business-info'>
            <h3 class='business-name'>
              <%= business.name %>
            </h3>
            <div class='business-price'>
              <span>  体験料  <%= business.price %>円<br><%= business.prefecture.name %></span>
              <div class='star-btn'>
              <% if user_signed_in? %>
                <% if business.favorited?(current_user) %>
                  <%= link_to business_favorites_path(id: business.id, business_id: business.id), method: :delete do %>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'><%= business.favorites.count %></span>
                  <% end %>
                <% else %>
                  <%= link_to business_favorites_path(id: business.id, business_id: business.id), method: :post do %>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'><%= business.favorites.count %></span>
                  <% end %>
                <% end %>
              <% else %>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'><%= business.favorites.count %></span>
              <% end %>
              </div>
            </div>
          </div>
      </li>
      <%end%>
    </ul>
  </div>
  <%# /体験一覧%>
</div>
  <%# 下部広告一覧%>
  <%= render "shared/footer" %>
  <%# /下部広告一覧%>

app/views/businesses/new.html.erb
<div class="businesses-new-contents">
  <header class="businesses-new-header">
  <%= link_to image_tag("logo.png", class: :logo, size: '160x60'), "/" %>
  </header>

  <div class="businesses-new-main">
    <h2 class="businesses-new-title">情報を入力してね！</h2>
    <%# 仕事体験紹介画像%>
    <%= render partial: 'shared/form' %>
    <%# /仕事体験紹介画像%>
  </div>

  <footer class="business-new-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('logo.png' , size: '185x50'), "/" %>
  </footer>

</div>

app/views/businesses/search.html.erb
<%= render "shared/header" %>
<h3>検索ページ</h3>
<h3><%= link_to 'トップページへ戻る', root_path%></h3>
<div class='business-contents' id="detailed-search-result-wrapper">
  <%= search_form_for @q, url: search_businesses_path, html: {id: "detailed-search-form"} do |f| %>
  <div class="search-field">
      <%= f.label :name, 'お仕事名' %>
      <br>
      <%= f.text_field :name, placeholder: 'お仕事名', value: params[:q]&.dig(:name) %>
    </div>
    <div class="search-field">
      <%= f.label :user_nickname_cont, '掲載者名' %>
      <br>
      <%= f.text_field :user_nickname_cont, placeholder: '掲載者名' %>
    </div>
    <div class="search-field">
      <%= f.label :prefecture_id_eq, '都道府県' %>
      <br>
      <%= f.collection_select(:prefecture_id_eq, Prefecture.all, :id, :name, {include_blank: "---"}) %>
    </div>
    <div class="search-field">
      <%= f.label :category_id_in, 'カテゴリ' %>
      <br>
      <%= f.collection_check_boxes(:category_id_in, Category.all, :id, :category, {include_blank: "---"}) %>
    </div>
    <div class="search-field">
      <%= f.label :price_gteq, '価格'%>
      <br>
      <%= f.number_field :price_gteq %> 円以上
      <br>
      <%= f.number_field :price_lteq %> 円以下
    </div>
    <%= f.submit '検索' %>
  <% end %>
  <ul class='business-lists' id="detailed-search-result">
    <% @business.each do |business| %>
      <li class='list'>
        <div class="posted-content">
        <%= link_to business_path(business.id) do %>
          <%= image_tag business.images[0], class: "business-img" %><br>
          <%= business.name%>
        <%end%>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/businesses/show.html.erb
<%= render "shared/header" %>

<%# 詳細画面%>
<div class="business-show">
  <div class="business-box">
    <h2 class="company">
      <%= @business.company%>
    </h2>
    <div class="business-img-content">
      <%= image_tag @business.images[0] ,class:"business-box-img"%>
      <div class="other-images">
        <% @business.images[1..-1].each do |image| %>
          <div class="other-image">
            <%= image_tag image %>
          </div>
        <%end%>
      </div>
    </div>
    <div class="business-price-box">
      <span class="business-price">
        ¥ <%= @business.price %>
      </span>
      <span class="business-name">
        <%= @business.name %>
      </span>
    </div>

    <div class="business-explain-box">
      <span><%= @business.text %></span>
    </div>
    <table class="detail-table">
      <tbody>
      <span class="underline-before"></span>
        <tr>
          <th class="detail-business">掲載者</th>
          <td class="detail-value"><%= @business.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-business">カテゴリー</th>
          <td class="detail-value"><%= @business.category.category %></td>
        </tr><tr>
          <th class="detail-business">都道府県</th>
          <td class="detail-value"><%= @business.prefecture.name %></td>
        </tr>
      </span>
      </tbody>
      </table>
    <div class="option">
      <div class="favorite-btn">
      <% if user_signed_in?%>
        <% if @business.favorited?(current_user) %>
        <%= link_to business_favorites_path(@business.id), method: :delete do %>
          <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"30",height:"30"%>
          <span>お気に入り<%= @business.favorites.count %></span>
          <% end %>
        <% else %>
        <%= link_to business_favorites_path(@business.id), method: :post do %>
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"30",height:"30"%>
          <span>お気に入り<%= @business.favorites.count %></span>
          <% end %>
        <% end %>
      <% else %>
      <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"30",height:"30"%>
      <span>お気に入り<%= @business.favorites.count %></span>
      <% end %>
      </div>
    </div>
    <% if user_signed_in? && @business.order == nil %>
      <%if current_user.id == @business.user.id %>
        <%= link_to "編集", edit_business_path, method: :get, class: "business-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", business_path(@business.id), method: :delete, class: "business-destroy" %>
    <%else%>
        <%= link_to "体験してみる", business_orders_path(@business), class: "business-red-btn" %>
      <%end%>
    <%end%>
  </div>

  <%# /詳細画面%>

  <div id="comments">
  <h4>＜コメント一覧＞</h4>
    <% @business.comments.each do |comment| %>
      <div class="comment">
        <p class="user-info"><%= comment.user.nickname %>： </p>
        <p><%= comment.text%></p>
      </div>
    <% end %>
</div>

  <div class="comment-form">
    <% if user_signed_in? %>
      <%= form_with model: [@business, @comment], id: "comment-form" do |f| %>
        <%= f.text_area :text , class: "comment-text"%>
        <%= f.submit "コメントをする", class: "comment-submit" %>
      <% end %>
    <% end %>
  </div>

  <a href="#" class="another-item"><%= @business.category.category %>をもっと見る</a>
</div>

<%= render "shared/footer" %>