config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: "businesses#index"
  
  resources :businesses do
    resources :orders, only: [:index, :create]
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: :create
      collection do
        get 'search'
      end
  end
  resources :users, only: [:show]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :prefecture

  belongs_to :user
  has_one :order
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many_attached :images
  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  with_options format: { with: /\A[0-9]+\z/ } do
    validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: "can't be blank" },
                      presence: { message: "can't be blank" }
  end

  validates :company, presence: true
  validates :name, presence: true
  validates :text, presence: true
  validates :category_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }
  validates :prefecture_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }
  validates :user, presence: true
  validates :images, presence: true
  validates :images, length: {minimum: 1, maximum: 5, message: "は1枚以上5枚以下にしてください" }
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, category: '---' }, { id: 2, category: '事務職' }, { id: 3, category: '販売職' },
    { id: 4, category: '専門的・技術的職' }, { id: 5, category: '生産工程職' }, { id: 6, category: 'サービス職' },
    { id: 7, category: '保安職' }, { id: 8, category: '建設・採掘職' }, { id: 9, category: '輸送・機械運転職' },
    { id: 10, category: '運搬・清掃・包装等職' }, { id: 11, category: '農林漁業職' }, { id: 12, category: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :businesses
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :business
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :business
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :business
  has_one :address
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :post_code, :prefecture_id, :city, :address, :building, :telephone, :user_id, :business_id, :token

  with_options presence: true do
    validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :post_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is invalid. Include hyphen(-)' }
    validates :city
    validates :address
    validates :telephone, format: { with: /\A\d{10,11}\z/, message: 'is invalid' }
    validates :business_id
    validates :user_id
    validates :token
  end

  def save
    order = Order.create(business_id: business_id, user_id: user_id)
    Address.create(post_code: post_code, prefecture_id: prefecture_id, city: city, address: address, building: building,
                   telephone: telephone, order_id: order.id)
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]
  include ActiveHash::Associations
  has_many :businesses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_many :businesses, dependent: :destroy
  has_many :comments
  has_many :favorites, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @business = Business.find(params[:business_id])
    if @comment.save
      CommentChannel.broadcast_to @business, { comment: @comment, user: @comment.user }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, business_id: params[:business_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @business_favorite = Favorite.new(user_id: current_user.id, business_id: params[:business_id])
    @business_favorite.save
    redirect_back fallback_location: root_path(params[:business_id])
  end

  def destroy
    @business_favorite = Favorite.find_by(user_id: current_user.id, business_id: params[:business_id])
    @business_favorite.destroy
    redirect_back fallback_location: root_path(params[:business_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:index, :create]
  before_action :move_to_index, only: [:index]

  def index
    @order_address = OrderAddress.new
  end

  def create
    @order_address = OrderAddress.new(order_params)
    if @order_address.valid?
      pay_item
      @order_address.save
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def set_item
    @business = Business.find(params[:business_id])
  end

  def order_params
    params.require(:order_address).permit(:post_code, :prefecture_id, :city, :address, :building, :telephone).merge(token: params[:token], user_id: current_user.id, business_id: params[:business_id]
    )
  end

  def pay_item
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    Payjp::Charge.create(
      amount: @business.price,
      card: order_params[:token],
      currency: 'jpy'
    )
  end

  def move_to_index
    redirect_to root_path if current_user.id == @business.user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @businesses = current_user.businesses
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeleru_helper.rb
module FeeleruHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feeleru2022</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分%>
<div class='footer'>
<p>©︎ FL</p>
</div>

app/views/shared/_form.html.erb
<%= form_with model: @business, id: 'new_business', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <div class="img-upload">
    <div class="weight-bold-text">
      職場体験画像
      <span class="indispensable">必須</span>
    </div>
    <div id="previews"></div>
    <div class="click-upload">
      <p>クリックしてファイルをアップロード</p>
      <%= f.file_field :images, name: 'business[images][]', data: {index: 0} %>
    </div>
        <%# 仕事名と内容紹介%>
    <div class="new-businesses">
      <div class="weight-bold-text">
        会社名
        <span class="indispensable">必須</span>
      </div>
        <%= f.text_area :company, class:"businesses-text", id:"company-name", placeholder:"会社名 屋号（必須)", maxlength:"40" %>
      <div class="weight-bold-text">
        職場体験名
        <span class="indispensable">必須</span>
      </div>
        <%= f.text_area :name, class:"businesses-text", id:"business-name", placeholder:"職場体験名（必須 40文字まで)", maxlength:"40" %>
      <div class="businesses-explain">
        <div class="weight-bold-text">
          仕事の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"businesses-text", id:"business-info", placeholder:"職場の説明（必須 1,000文字まで）(体験の特徴、体験先について) ITを活用したイチゴ栽培が特徴です！ 山と川に囲まれた自然豊かな環境！" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /仕事名と内容紹介%>
    <%# 仕事詳細%>
    <div class="businesses-detail">
      <div class="weight-bold-text">仕事の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
        カテゴリー
        <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :category, {}, {class:"select-box", id:"business-category"}) %>
        <div class="weight-bold-text">
        都道府県
        <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
      </div>
    </div>
    <%# /仕事詳細%>
    <%# 販売価格%>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"business-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格%>
    <%# 下部ボタン%>
    <div class="sell-btn-contents">
      <%= f.submit "掲載する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン%>
  </div>
  </div>
<%end%>

app/views/shared/_header.html.erb
<header class="header">
  <div class="inner">
    <div class="nav">
      <div class="nav__left">
      <%= link_to image_tag("logo.png", class: :logo), root_path %>
      </div>
      <div class='search-bar-contents'>
        <%= search_form_for Business.ransack(params[:q]), url: search_businesses_path, html: {class: "search-form"} do |f| %>
          <%= f.text_field :name, placeholder: 'お仕事名から探す', class: 'input-box' %>
          <br>
          <%= f.label :submit, class: "search-button" do %>
            <input type="submit" value="検索" class="send">
            <%= f.submit :submit, id: "q_submit", style: "display: none;"%>
          <% end %>
        <% end %>
      </div>

        <%# ログインしているときは以下を表示する %>
      <% if user_signed_in? %>
        <div class="nav__right">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
          <%= link_to "マイページ", user_path(current_user), class: :nav__btn %>
          <%= link_to "掲載する", new_business_path, class: :nav__btn %>
          <%= link_to '検索する', search_businesses_path%>
          <%= link_to "#{current_user.nickname}さん", "#", class: "user-nickname"%>
        </div>
        <%# // ログインしているときは上記を表示する %>
      <% else %>
        <%# ログインしていないときは以下を表示する %>
        <div class="nav__right">
          <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
          <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
          <%= link_to "掲載する", new_business_path, class: :nav__btn %>
          <%= link_to '検索する', search_businesses_path%>
        </div>
      <% end %>
      <div class="nav__right">
      <%= link_to image_tag("Twitter social icons - circle - blue.png",class: :twitter_logo, size: '40x40'), '/' %>
      </div>
        <%# // ログインしていないときは上記を表示する %>
    </div>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", size: '160x60', class: "second-logo"), "/" %>
</header>